window.NEIGHBORHOODS_REGISTRY = [
  {
    "id": "central-west-end",
    "title": "Central West End, St. Louis",
    "summary": "Central West End neighborhood guide for buyers: location, housing character, market data, and what to know before searching this St. Louis City area.",
    "url": "neighborhoods/central-west-end.html",
    "type": "neighborhood",
    "slug": "central-west-end",
    "group": "St. Louis City",
    "tag": "West End",
    "zips": ["63108"],
    "status": "published",
    "indexable": true,
    "template": "neighborhood"
  },
  {
    "id": "tower-grove-south",
    "title": "Tower Grove South, St. Louis",
    "summary": "Tower Grove South neighborhood guide for buyers: location, housing character, market data, and what to know before searching this St. Louis City area.",
    "url": "neighborhoods/tower-grove-south.html",
    "type": "neighborhood",
    "slug": "tower-grove-south",
    "group": "St. Louis City",
    "tag": "South City",
    "zips": ["63116"],
    "status": "published",
    "indexable": true,
    "template": "neighborhood"
  },
  {
    "id": "shaw",
    "title": "Shaw, St. Louis",
    "summary": "Shaw neighborhood guide for buyers: location, housing character, market data, and what to know before searching this St. Louis City area.",
    "url": "neighborhoods/shaw.html",
    "type": "neighborhood",
    "slug": "shaw",
    "group": "St. Louis City",
    "tag": "Southwest City",
    "zips": ["63110"],
    "status": "published",
    "indexable": true,
    "template": "neighborhood"
  },
  {
    "id": "dogtown",
    "title": "Dogtown, St. Louis",
    "summary": "Dogtown neighborhood guide for buyers: location, housing character, market data, and what to know before searching this St. Louis City area.",
    "url": "neighborhoods/dogtown.html",
    "type": "neighborhood",
    "slug": "dogtown",
    "group": "St. Louis City",
    "tag": "Southwest City",
    "zips": ["63139"],
    "status": "published",
    "indexable": true,
    "template": "neighborhood"
  },
  {
    "id": "soulard",
    "title": "Soulard, St. Louis",
    "summary": "Soulard neighborhood guide for buyers: location, housing character, market data, and what to know before searching this St. Louis City area.",
    "url": "neighborhoods/soulard.html",
    "type": "neighborhood",
    "slug": "soulard",
    "group": "St. Louis City",
    "tag": "South City",
    "zips": ["63104"],
    "status": "published",
    "indexable": true,
    "template": "neighborhood"
  },
  {
    "id": "lafayette-square",
    "title": "Lafayette Square, St. Louis",
    "summary": "Lafayette Square neighborhood guide for buyers: location, housing character, market data, and what to know before searching this St. Louis City area.",
    "url": "neighborhoods/lafayette-square.html",
    "type": "neighborhood",
    "slug": "lafayette-square",
    "group": "St. Louis City",
    "tag": "Midtown",
    "zips": ["63104"],
    "status": "published",
    "indexable": true,
    "template": "neighborhood"
  },
  {
    "id": "the-hill",
    "title": "The Hill, St. Louis",
    "summary": "The Hill neighborhood guide for buyers: location, housing character, market data, and what to know before searching this St. Louis City area.",
    "url": "neighborhoods/the-hill.html",
    "type": "neighborhood",
    "slug": "the-hill",
    "group": "St. Louis City",
    "tag": "Southwest City",
    "zips": ["63110"],
    "status": "published",
    "indexable": true,
    "template": "neighborhood"
  },
  {
    "id": "benton-park",
    "title": "Benton Park, St. Louis",
    "summary": "Benton Park neighborhood guide for buyers: location, housing character, market data, and what to know before searching this St. Louis City area.",
    "url": "neighborhoods/benton-park.html",
    "type": "neighborhood",
    "slug": "benton-park",
    "group": "St. Louis City",
    "tag": "South City",
    "zips": ["63118"],
    "status": "published",
    "indexable": true,
    "template": "neighborhood"
  },
  {
    "id": "st-louis-hills",
    "title": "St. Louis Hills, St. Louis",
    "summary": "St. Louis Hills neighborhood guide for buyers: location, housing character, market data, and what to know before searching this St. Louis City area.",
    "url": "neighborhoods/st-louis-hills.html",
    "type": "neighborhood",
    "slug": "st-louis-hills",
    "group": "St. Louis City",
    "tag": "South City",
    "zips": ["63109"],
    "status": "published",
    "indexable": true,
    "template": "neighborhood"
  },
  {
    "id": "kirkwood",
    "title": "Kirkwood, Missouri",
    "summary": "Kirkwood neighborhood guide for buyers: location, housing character, market data, and what to know before searching this Central Corridor area.",
    "url": "neighborhoods/kirkwood.html",
    "type": "neighborhood",
    "slug": "kirkwood",
    "group": "Central Corridor",
    "tag": "Inner West",
    "zips": ["63122"],
    "status": "published",
    "indexable": true,
    "template": "neighborhood"
  },
  {
    "id": "webster-groves",
    "title": "Webster Groves, Missouri",
    "summary": "Webster Groves neighborhood guide for buyers: location, housing character, market data, and what to know before searching this Central Corridor area.",
    "url": "neighborhoods/webster-groves.html",
    "type": "neighborhood",
    "slug": "webster-groves",
    "group": "Central Corridor",
    "tag": "Inner West",
    "zips": ["63119"],
    "status": "published",
    "indexable": true,
    "template": "neighborhood"
  },
  {
    "id": "clayton",
    "title": "Clayton, Missouri",
    "summary": "Clayton neighborhood guide for buyers: location, housing character, market data, and what to know before searching this Central Corridor area.",
    "url": "neighborhoods/clayton.html",
    "type": "neighborhood",
    "slug": "clayton",
    "group": "Central Corridor",
    "tag": "Inner West",
    "zips": ["63105"],
    "status": "published",
    "indexable": true,
    "template": "neighborhood"
  },
  {
    "id": "university-city",
    "title": "University City, Missouri",
    "summary": "University City neighborhood guide for buyers: location, housing character, market data, and what to know before searching this Central Corridor area.",
    "url": "neighborhoods/university-city.html",
    "type": "neighborhood",
    "slug": "university-city",
    "group": "Central Corridor",
    "tag": "Inner West",
    "zips": ["63130", "63133"],
    "status": "published",
    "indexable": true,
    "template": "neighborhood"
  },
  {
    "id": "maplewood",
    "title": "Maplewood, Missouri",
    "summary": "Maplewood neighborhood guide for buyers: location, housing character, market data, and what to know before searching this Central Corridor area.",
    "url": "neighborhoods/maplewood.html",
    "type": "neighborhood",
    "slug": "maplewood",
    "group": "Central Corridor",
    "tag": "Inner West",
    "zips": ["63143"],
    "status": "published",
    "indexable": true,
    "template": "neighborhood"
  },
  {
    "id": "florissant",
    "title": "Florissant, Missouri",
    "summary": "Florissant neighborhood guide for buyers: location, housing character, market data, and what to know before searching this North County area.",
    "url": "neighborhoods/florissant.html",
    "type": "neighborhood",
    "slug": "florissant",
    "group": "North County",
    "tag": "North County",
    "zips": ["63031", "63033", "63034"],
    "status": "published",
    "indexable": true,
    "template": "neighborhood"
  },
  {
    "id": "ferguson",
    "title": "Ferguson, Missouri",
    "summary": "Ferguson neighborhood guide for buyers: location, housing character, market data, and what to know before searching this North County area.",
    "url": "neighborhoods/ferguson.html",
    "type": "neighborhood",
    "slug": "ferguson",
    "group": "North County",
    "tag": "North County",
    "zips": ["63135"],
    "status": "published",
    "indexable": true,
    "template": "neighborhood"
  },
  {
    "id": "hazelwood",
    "title": "Hazelwood, Missouri",
    "summary": "Hazelwood neighborhood guide for buyers: location, housing character, market data, and what to know before searching this North County area.",
    "url": "neighborhoods/hazelwood.html",
    "type": "neighborhood",
    "slug": "hazelwood",
    "group": "North County",
    "tag": "North County",
    "zips": ["63042"],
    "status": "published",
    "indexable": true,
    "template": "neighborhood"
  },
  {
    "id": "jennings",
    "title": "Jennings, Missouri",
    "summary": "Jennings neighborhood guide for buyers: location, housing character, market data, and what to know before searching this North County area.",
    "url": "neighborhoods/jennings.html",
    "type": "neighborhood",
    "slug": "jennings",
    "group": "North County",
    "tag": "North County",
    "zips": ["63136"],
    "status": "published",
    "indexable": true,
    "template": "neighborhood"
  },
  {
    "id": "spanish-lake",
    "title": "Spanish Lake, Missouri",
    "summary": "Spanish Lake neighborhood guide for buyers: location, housing character, market data, and what to know before searching this North County area.",
    "url": "neighborhoods/spanish-lake.html",
    "type": "neighborhood",
    "slug": "spanish-lake",
    "group": "North County",
    "tag": "North County",
    "zips": ["63138"],
    "status": "published",
    "indexable": true,
    "template": "neighborhood"
  },
  {
    "id": "riverview",
    "title": "Riverview, Missouri",
    "summary": "Riverview neighborhood guide for buyers: location, housing character, market data, and what to know before searching this North County area.",
    "url": "neighborhoods/riverview.html",
    "type": "neighborhood",
    "slug": "riverview",
    "group": "North County",
    "tag": "North County",
    "zips": ["63137"],
    "status": "published",
    "indexable": true,
    "template": "neighborhood"
  },
  {
    "id": "berkeley",
    "title": "Berkeley, Missouri",
    "summary": "Berkeley neighborhood guide for buyers: location, housing character, market data, and what to know before searching this North County area.",
    "url": "neighborhoods/berkeley.html",
    "type": "neighborhood",
    "slug": "berkeley",
    "group": "North County",
    "tag": "North County",
    "zips": ["63134"],
    "status": "published",
    "indexable": true,
    "template": "neighborhood"
  },
  {
    "id": "bridgeton",
    "title": "Bridgeton, Missouri",
    "summary": "Bridgeton neighborhood guide for buyers: location, housing character, market data, and what to know before searching this North County area.",
    "url": "neighborhoods/bridgeton.html",
    "type": "neighborhood",
    "slug": "bridgeton",
    "group": "North County",
    "tag": "North County",
    "zips": ["63044"],
    "status": "published",
    "indexable": true,
    "template": "neighborhood"
  },
  {
    "id": "st-ann",
    "title": "St. Ann, Missouri",
    "summary": "St. Ann neighborhood guide for buyers: location, housing character, market data, and what to know before searching this North County area.",
    "url": "neighborhoods/st-ann.html",
    "type": "neighborhood",
    "slug": "st-ann",
    "group": "North County",
    "tag": "North County",
    "zips": ["63074"],
    "status": "published",
    "indexable": true,
    "template": "neighborhood"
  },
  {
    "id": "st-john",
    "title": "St. John, Missouri",
    "summary": "St. John neighborhood guide for buyers: location, housing character, market data, and what to know before searching this North County area.",
    "url": "neighborhoods/st-john.html",
    "type": "neighborhood",
    "slug": "st-john",
    "group": "North County",
    "tag": "North County",
    "zips": ["63114"],
    "status": "published",
    "indexable": true,
    "template": "neighborhood"
  },
  {
    "id": "normandy",
    "title": "Normandy, Missouri",
    "summary": "Normandy neighborhood guide for buyers: location, housing character, market data, and what to know before searching this North County area.",
    "url": "neighborhoods/normandy.html",
    "type": "neighborhood",
    "slug": "normandy",
    "group": "North County",
    "tag": "North County",
    "zips": ["63121"],
    "status": "published",
    "indexable": true,
    "template": "neighborhood"
  },
  {
    "id": "black-jack",
    "title": "Black Jack, Missouri",
    "summary": "Black Jack neighborhood guide for buyers: location, housing character, market data, and what to know before searching this North County area.",
    "url": "neighborhoods/black-jack.html",
    "type": "neighborhood",
    "slug": "black-jack",
    "group": "North County",
    "tag": "North County",
    "zips": ["63033"],
    "status": "published",
    "indexable": true,
    "template": "neighborhood"
  },
  {
    "id": "dellwood",
    "title": "Dellwood, Missouri",
    "summary": "Dellwood neighborhood guide for buyers: location, housing character, market data, and what to know before searching this North County area.",
    "url": "neighborhoods/dellwood.html",
    "type": "neighborhood",
    "slug": "dellwood",
    "group": "North County",
    "tag": "North County",
    "zips": ["63135"],
    "status": "published",
    "indexable": true,
    "template": "neighborhood"
  },
  {
    "id": "moline-acres",
    "title": "Moline Acres, Missouri",
    "summary": "Moline Acres neighborhood guide for buyers: location, housing character, market data, and what to know before searching this North County area.",
    "url": "neighborhoods/moline-acres.html",
    "type": "neighborhood",
    "slug": "moline-acres",
    "group": "North County",
    "tag": "North County",
    "zips": ["63136"],
    "status": "published",
    "indexable": true,
    "template": "neighborhood"
  },
  {
    "id": "cool-valley",
    "title": "Cool Valley, Missouri",
    "summary": "Cool Valley neighborhood guide for buyers: location, housing character, market data, and what to know before searching this North County area.",
    "url": "neighborhoods/cool-valley.html",
    "type": "neighborhood",
    "slug": "cool-valley",
    "group": "North County",
    "tag": "North County",
    "zips": ["63121"],
    "status": "published",
    "indexable": true,
    "template": "neighborhood"
  },
  {
    "id": "pagedale",
    "title": "Pagedale, Missouri",
    "summary": "Pagedale neighborhood guide for buyers: location, housing character, market data, and what to know before searching this North County area.",
    "url": "neighborhoods/pagedale.html",
    "type": "neighborhood",
    "slug": "pagedale",
    "group": "North County",
    "tag": "North County",
    "zips": ["63133"],
    "status": "published",
    "indexable": true,
    "template": "neighborhood"
  },
  {
    "id": "wellston",
    "title": "Wellston, Missouri",
    "summary": "Wellston neighborhood guide for buyers: location, housing character, market data, and what to know before searching this North County area.",
    "url": "neighborhoods/wellston.html",
    "type": "neighborhood",
    "slug": "wellston",
    "group": "North County",
    "tag": "North County",
    "zips": ["63133"],
    "status": "published",
    "indexable": true,
    "template": "neighborhood"
  },
  {
    "id": "pine-lawn",
    "title": "Pine Lawn, Missouri",
    "summary": "Pine Lawn neighborhood guide for buyers: location, housing character, market data, and what to know before searching this North County area.",
    "url": "neighborhoods/pine-lawn.html",
    "type": "neighborhood",
    "slug": "pine-lawn",
    "group": "North County",
    "tag": "North County",
    "zips": ["63120"],
    "status": "published",
    "indexable": true,
    "template": "neighborhood"
  },
  {
    "id": "bel-nor",
    "title": "Bel-Nor, Missouri",
    "summary": "Bel-Nor neighborhood guide for buyers: location, housing character, market data, and what to know before searching this North County area.",
    "url": "neighborhoods/bel-nor.html",
    "type": "neighborhood",
    "slug": "bel-nor",
    "group": "North County",
    "tag": "North County",
    "zips": ["63121"],
    "status": "published",
    "indexable": true,
    "template": "neighborhood"
  },
  {
    "id": "bel-ridge",
    "title": "Bel-Ridge, Missouri",
    "summary": "Bel-Ridge neighborhood guide for buyers: location, housing character, market data, and what to know before searching this North County area.",
    "url": "neighborhoods/bel-ridge.html",
    "type": "neighborhood",
    "slug": "bel-ridge",
    "group": "North County",
    "tag": "North County",
    "zips": ["63121"],
    "status": "published",
    "indexable": true,
    "template": "neighborhood"
  },
  {
    "id": "bellefontaine-neighbors",
    "title": "Bellefontaine Neighbors, Missouri",
    "summary": "Bellefontaine Neighbors neighborhood guide for buyers: location, housing character, market data, and what to know before searching this North County area.",
    "url": "neighborhoods/bellefontaine-neighbors.html",
    "type": "neighborhood",
    "slug": "bellefontaine-neighbors",
    "group": "North County",
    "tag": "North County",
    "zips": ["63137"],
    "status": "published",
    "indexable": true,
    "template": "neighborhood"
  },
  {
    "id": "calverton-park",
    "title": "Calverton Park, Missouri",
    "summary": "Calverton Park neighborhood guide for buyers: location, housing character, market data, and what to know before searching this North County area.",
    "url": "neighborhoods/calverton-park.html",
    "type": "neighborhood",
    "slug": "calverton-park",
    "group": "North County",
    "tag": "North County",
    "zips": ["63033"],
    "status": "published",
    "indexable": true,
    "template": "neighborhood"
  },
  {
    "id": "castle-point",
    "title": "Castle Point, Missouri",
    "summary": "Castle Point neighborhood guide for buyers: location, housing character, market data, and what to know before searching this North County area.",
    "url": "neighborhoods/castle-point.html",
    "type": "neighborhood",
    "slug": "castle-point",
    "group": "North County",
    "tag": "North County",
    "zips": ["63136"],
    "status": "published",
    "indexable": true,
    "template": "neighborhood"
  },
  {
    "id": "country-club-hills",
    "title": "Country Club Hills, Missouri",
    "summary": "Country Club Hills neighborhood guide for buyers: location, housing character, market data, and what to know before searching this North County area.",
    "url": "neighborhoods/country-club-hills.html",
    "type": "neighborhood",
    "slug": "country-club-hills",
    "group": "North County",
    "tag": "North County",
    "zips": ["63136"],
    "status": "published",
    "indexable": true,
    "template": "neighborhood"
  },
  {
    "id": "edmundson",
    "title": "Edmundson, Missouri",
    "summary": "Edmundson neighborhood guide for buyers: location, housing character, market data, and what to know before searching this North County area.",
    "url": "neighborhoods/edmundson.html",
    "type": "neighborhood",
    "slug": "edmundson",
    "group": "North County",
    "tag": "North County",
    "zips": ["63134"],
    "status": "published",
    "indexable": true,
    "template": "neighborhood"
  },
  {
    "id": "flordell-hills",
    "title": "Flordell Hills, Missouri",
    "summary": "Flordell Hills neighborhood guide for buyers: location, housing character, market data, and what to know before searching this North County area.",
    "url": "neighborhoods/flordell-hills.html",
    "type": "neighborhood",
    "slug": "flordell-hills",
    "group": "North County",
    "tag": "North County",
    "zips": ["63136"],
    "status": "published",
    "indexable": true,
    "template": "neighborhood"
  },
  {
    "id": "glen-echo-park",
    "title": "Glen Echo Park, Missouri",
    "summary": "Glen Echo Park neighborhood guide for buyers: location, housing character, market data, and what to know before searching this North County area.",
    "url": "neighborhoods/glen-echo-park.html",
    "type": "neighborhood",
    "slug": "glen-echo-park",
    "group": "North County",
    "tag": "North County",
    "zips": ["63136"],
    "status": "published",
    "indexable": true,
    "template": "neighborhood"
  },
  {
    "id": "greendale",
    "title": "Greendale, Missouri",
    "summary": "Greendale neighborhood guide for buyers: location, housing character, market data, and what to know before searching this North County area.",
    "url": "neighborhoods/greendale.html",
    "type": "neighborhood",
    "slug": "greendale",
    "group": "North County",
    "tag": "North County",
    "zips": ["63136"],
    "status": "published",
    "indexable": true,
    "template": "neighborhood"
  },
  {
    "id": "hanley-hills",
    "title": "Hanley Hills, Missouri",
    "summary": "Hanley Hills neighborhood guide for buyers: location, housing character, market data, and what to know before searching this North County area.",
    "url": "neighborhoods/hanley-hills.html",
    "type": "neighborhood",
    "slug": "hanley-hills",
    "group": "North County",
    "tag": "North County",
    "zips": ["63133"],
    "status": "published",
    "indexable": true,
    "template": "neighborhood"
  },
  {
    "id": "hillsdale",
    "title": "Hillsdale, Missouri",
    "summary": "Hillsdale neighborhood guide for buyers: location, housing character, market data, and what to know before searching this North County area.",
    "url": "neighborhoods/hillsdale.html",
    "type": "neighborhood",
    "slug": "hillsdale",
    "group": "North County",
    "tag": "North County",
    "zips": ["63121"],
    "status": "published",
    "indexable": true,
    "template": "neighborhood"
  },
  {
    "id": "norwood-court",
    "title": "Norwood Court, Missouri",
    "summary": "Norwood Court neighborhood guide for buyers: location, housing character, market data, and what to know before searching this North County area.",
    "url": "neighborhoods/norwood-court.html",
    "type": "neighborhood",
    "slug": "norwood-court",
    "group": "North County",
    "tag": "North County",
    "zips": ["63121"],
    "status": "published",
    "indexable": true,
    "template": "neighborhood"
  },
  {
    "id": "northwoods",
    "title": "Northwoods, Missouri",
    "summary": "Northwoods neighborhood guide for buyers: location, housing character, market data, and what to know before searching this North County area.",
    "url": "neighborhoods/northwoods.html",
    "type": "neighborhood",
    "slug": "northwoods",
    "group": "North County",
    "tag": "North County",
    "zips": ["63121"],
    "status": "published",
    "indexable": true,
    "template": "neighborhood"
  },
  {
    "id": "olympian-village",
    "title": "Olympian Village, Missouri",
    "summary": "Olympian Village neighborhood guide for buyers: location, housing character, market data, and what to know before searching this North County area.",
    "url": "neighborhoods/olympian-village.html",
    "type": "neighborhood",
    "slug": "olympian-village",
    "group": "North County",
    "tag": "North County",
    "zips": ["63121"],
    "status": "published",
    "indexable": true,
    "template": "neighborhood"
  },
  {
    "id": "parkdale",
    "title": "Parkdale, Missouri",
    "summary": "Parkdale neighborhood guide for buyers: location, housing character, market data, and what to know before searching this North County area.",
    "url": "neighborhoods/parkdale.html",
    "type": "neighborhood",
    "slug": "parkdale",
    "group": "North County",
    "tag": "North County",
    "zips": ["63121"],
    "status": "published",
    "indexable": true,
    "template": "neighborhood"
  },
  {
    "id": "pasadena-hills",
    "title": "Pasadena Hills, Missouri",
    "summary": "Pasadena Hills neighborhood guide for buyers: location, housing character, market data, and what to know before searching this North County area.",
    "url": "neighborhoods/pasadena-hills.html",
    "type": "neighborhood",
    "slug": "pasadena-hills",
    "group": "North County",
    "tag": "North County",
    "zips": ["63121"],
    "status": "published",
    "indexable": true,
    "template": "neighborhood"
  },
  {
    "id": "pasadena-park",
    "title": "Pasadena Park, Missouri",
    "summary": "Pasadena Park neighborhood guide for buyers: location, housing character, market data, and what to know before searching this North County area.",
    "url": "neighborhoods/pasadena-park.html",
    "type": "neighborhood",
    "slug": "pasadena-park",
    "group": "North County",
    "tag": "North County",
    "zips": ["63121"],
    "status": "published",
    "indexable": true,
    "template": "neighborhood"
  },
  {
    "id": "peaceful-village",
    "title": "Peaceful Village, Missouri",
    "summary": "Peaceful Village neighborhood guide for buyers: location, housing character, market data, and what to know before searching this North County area.",
    "url": "neighborhoods/peaceful-village.html",
    "type": "neighborhood",
    "slug": "peaceful-village",
    "group": "North County",
    "tag": "North County",
    "zips": ["63136"],
    "status": "published",
    "indexable": true,
    "template": "neighborhood"
  },
  {
    "id": "scotsdale",
    "title": "Scotsdale, Missouri",
    "summary": "Scotsdale neighborhood guide for buyers: location, housing character, market data, and what to know before searching this North County area.",
    "url": "neighborhoods/scotsdale.html",
    "type": "neighborhood",
    "slug": "scotsdale",
    "group": "North County",
    "tag": "North County",
    "zips": ["63033"],
    "status": "published",
    "indexable": true,
    "template": "neighborhood"
  },
  {
    "id": "sycamore-hills",
    "title": "Sycamore Hills, Missouri",
    "summary": "Sycamore Hills neighborhood guide for buyers: location, housing character, market data, and what to know before searching this North County area.",
    "url": "neighborhoods/sycamore-hills.html",
    "type": "neighborhood",
    "slug": "sycamore-hills",
    "group": "North County",
    "tag": "North County",
    "zips": ["63114"],
    "status": "published",
    "indexable": true,
    "template": "neighborhood"
  },
  {
    "id": "uplands-park",
    "title": "Uplands Park, Missouri",
    "summary": "Uplands Park neighborhood guide for buyers: location, housing character, market data, and what to know before searching this North County area.",
    "url": "neighborhoods/uplands-park.html",
    "type": "neighborhood",
    "slug": "uplands-park",
    "group": "North County",
    "tag": "North County",
    "zips": ["63121"],
    "status": "published",
    "indexable": true,
    "template": "neighborhood"
  },
  {
    "id": "velda-city",
    "title": "Velda City, Missouri",
    "summary": "Velda City neighborhood guide for buyers: location, housing character, market data, and what to know before searching this North County area.",
    "url": "neighborhoods/velda-city.html",
    "type": "neighborhood",
    "slug": "velda-city",
    "group": "North County",
    "tag": "North County",
    "zips": ["63121"],
    "status": "published",
    "indexable": true,
    "template": "neighborhood"
  },
  {
    "id": "velda-village-hills",
    "title": "Velda Village Hills, Missouri",
    "summary": "Velda Village Hills neighborhood guide for buyers: location, housing character, market data, and what to know before searching this North County area.",
    "url": "neighborhoods/velda-village-hills.html",
    "type": "neighborhood",
    "slug": "velda-village-hills",
    "group": "North County",
    "tag": "North County",
    "zips": ["63121"],
    "status": "published",
    "indexable": true,
    "template": "neighborhood"
  },
  {
    "id": "vinita-park",
    "title": "Vinita Park, Missouri",
    "summary": "Vinita Park neighborhood guide for buyers: location, housing character, market data, and what to know before searching this North County area.",
    "url": "neighborhoods/vinita-park.html",
    "type": "neighborhood",
    "slug": "vinita-park",
    "group": "North County",
    "tag": "North County",
    "zips": ["63114"],
    "status": "published",
    "indexable": true,
    "template": "neighborhood"
  },
  {
    "id": "vinita-terrace",
    "title": "Vinita Terrace, Missouri",
    "summary": "Vinita Terrace neighborhood guide for buyers: location, housing character, market data, and what to know before searching this North County area.",
    "url": "neighborhoods/vinita-terrace.html",
    "type": "neighborhood",
    "slug": "vinita-terrace",
    "group": "North County",
    "tag": "North County",
    "zips": ["63121"],
    "status": "published",
    "indexable": true,
    "template": "neighborhood"
  },
  {
    "id": "woodson-terrace",
    "title": "Woodson Terrace, Missouri",
    "summary": "Woodson Terrace neighborhood guide for buyers: location, housing character, market data, and what to know before searching this North County area.",
    "url": "neighborhoods/woodson-terrace.html",
    "type": "neighborhood",
    "slug": "woodson-terrace",
    "group": "North County",
    "tag": "North County",
    "zips": ["63134"],
    "status": "published",
    "indexable": true,
    "template": "neighborhood"
  },
  {
    "id": "charlack",
    "title": "Charlack, Missouri",
    "summary": "Charlack neighborhood guide for buyers: location, housing character, market data, and what to know before searching this North County area.",
    "url": "neighborhoods/charlack.html",
    "type": "neighborhood",
    "slug": "charlack",
    "group": "North County",
    "tag": "North County",
    "zips": ["63114"],
    "status": "published",
    "indexable": true,
    "template": "neighborhood"
  },
  {
    "id": "champ",
    "title": "Champ, Missouri",
    "summary": "Champ neighborhood guide for buyers: location, housing character, market data, and what to know before searching this North County area.",
    "url": "neighborhoods/champ.html",
    "type": "neighborhood",
    "slug": "champ",
    "group": "North County",
    "tag": "North County",
    "zips": ["63114"],
    "status": "published",
    "indexable": true,
    "template": "neighborhood"
  },
  {
    "id": "breckenridge-hills",
    "title": "Breckenridge Hills, Missouri",
    "summary": "Breckenridge Hills neighborhood guide for buyers: location, housing character, market data, and what to know before searching this North County area.",
    "url": "neighborhoods/breckenridge-hills.html",
    "type": "neighborhood",
    "slug": "breckenridge-hills",
    "group": "North County",
    "tag": "North County",
    "zips": ["63114"],
    "status": "published",
    "indexable": true,
    "template": "neighborhood"
  },
  {
    "id": "bellerive-acres",
    "title": "Bellerive Acres, Missouri",
    "summary": "Bellerive Acres neighborhood guide for buyers: location, housing character, market data, and what to know before searching this North County area.",
    "url": "neighborhoods/bellerive-acres.html",
    "type": "neighborhood",
    "slug": "bellerive-acres",
    "group": "North County",
    "tag": "North County",
    "zips": ["63121"],
    "status": "published",
    "indexable": true,
    "template": "neighborhood"
  },
  {
    "id": "beverly-hills",
    "title": "Beverly Hills, Missouri",
    "summary": "Beverly Hills neighborhood guide for buyers: location, housing character, market data, and what to know before searching this North County area.",
    "url": "neighborhoods/beverly-hills.html",
    "type": "neighborhood",
    "slug": "beverly-hills",
    "group": "North County",
    "tag": "North County",
    "zips": ["63121"],
    "status": "published",
    "indexable": true,
    "template": "neighborhood"
  },
  {
    "id": "normandy-park",
    "title": "Normandy Park, Missouri",
    "summary": "Normandy Park neighborhood guide for buyers: location, housing character, market data, and what to know before searching this North County area.",
    "url": "neighborhoods/normandy-park.html",
    "type": "neighborhood",
    "slug": "normandy-park",
    "group": "North County",
    "tag": "North County",
    "zips": ["63121"],
    "status": "published",
    "indexable": true,
    "template": "neighborhood"
  },
  {
    "id": "affton",
    "title": "Affton, Missouri",
    "summary": "Affton neighborhood guide for buyers: location, housing character, market data, and what to know before searching this South County area.",
    "url": "neighborhoods/affton.html",
    "type": "neighborhood",
    "slug": "affton",
    "group": "South County",
    "tag": "South County",
    "zips": ["63123"],
    "status": "published",
    "indexable": true,
    "template": "neighborhood"
  },
  {
    "id": "concord",
    "title": "Concord, Missouri",
    "summary": "Concord neighborhood guide for buyers: location, housing character, market data, and what to know before searching this South County area.",
    "url": "neighborhoods/concord.html",
    "type": "neighborhood",
    "slug": "concord",
    "group": "South County",
    "tag": "South County",
    "zips": ["63128", "63123"],
    "status": "published",
    "indexable": true,
    "template": "neighborhood"
  },
  {
    "id": "crestwood",
    "title": "Crestwood, Missouri",
    "summary": "Crestwood neighborhood guide for buyers: location, housing character, market data, and what to know before searching this South County area.",
    "url": "neighborhoods/crestwood.html",
    "type": "neighborhood",
    "slug": "crestwood",
    "group": "South County",
    "tag": "South County",
    "zips": ["63126"],
    "status": "published",
    "indexable": true,
    "template": "neighborhood"
  },
  {
    "id": "green-park",
    "title": "Green Park, Missouri",
    "summary": "Green Park neighborhood guide for buyers: location, housing character, market data, and what to know before searching this South County area.",
    "url": "neighborhoods/green-park.html",
    "type": "neighborhood",
    "slug": "green-park",
    "group": "South County",
    "tag": "South County",
    "zips": ["63123"],
    "status": "published",
    "indexable": true,
    "template": "neighborhood"
  },
  {
    "id": "lemay",
    "title": "Lemay, Missouri",
    "summary": "Lemay neighborhood guide for buyers: location, housing character, market data, and what to know before searching this South County area.",
    "url": "neighborhoods/lemay.html",
    "type": "neighborhood",
    "slug": "lemay",
    "group": "South County",
    "tag": "South County",
    "zips": ["63125"],
    "status": "published",
    "indexable": true,
    "template": "neighborhood"
  },
  {
    "id": "mehlville",
    "title": "Mehlville, Missouri",
    "summary": "Mehlville neighborhood guide for buyers: location, housing character, market data, and what to know before searching this South County area.",
    "url": "neighborhoods/mehlville.html",
    "type": "neighborhood",
    "slug": "mehlville",
    "group": "South County",
    "tag": "South County",
    "zips": ["63125"],
    "status": "published",
    "indexable": true,
    "template": "neighborhood"
  },
  {
    "id": "oakville",
    "title": "Oakville, Missouri",
    "summary": "Oakville neighborhood guide for buyers: location, housing character, market data, and what to know before searching this South County area.",
    "url": "neighborhoods/oakville.html",
    "type": "neighborhood",
    "slug": "oakville",
    "group": "South County",
    "tag": "South County",
    "zips": ["63129"],
    "status": "published",
    "indexable": true,
    "template": "neighborhood"
  },
  {
    "id": "sappington",
    "title": "Sappington, Missouri",
    "summary": "Sappington neighborhood guide for buyers: location, housing character, market data, and what to know before searching this South County area.",
    "url": "neighborhoods/sappington.html",
    "type": "neighborhood",
    "slug": "sappington",
    "group": "South County",
    "tag": "South County",
    "zips": ["63126", "63128"],
    "status": "published",
    "indexable": true,
    "template": "neighborhood"
  },
  {
    "id": "sunset-hills",
    "title": "Sunset Hills, Missouri",
    "summary": "Sunset Hills neighborhood guide for buyers: location, housing character, market data, and what to know before searching this South County area.",
    "url": "neighborhoods/sunset-hills.html",
    "type": "neighborhood",
    "slug": "sunset-hills",
    "group": "South County",
    "tag": "South County",
    "zips": ["63127"],
    "status": "published",
    "indexable": true,
    "template": "neighborhood"
  },
  {
    "id": "ballwin",
    "title": "Ballwin, Missouri",
    "summary": "Ballwin neighborhood guide for buyers: location, housing character, market data, and what to know before searching this West County area.",
    "url": "neighborhoods/ballwin.html",
    "type": "neighborhood",
    "slug": "ballwin",
    "group": "West County",
    "tag": "West County",
    "zips": ["63011", "63021"],
    "status": "published",
    "indexable": true,
    "template": "neighborhood"
  },
  {
    "id": "chesterfield",
    "title": "Chesterfield, Missouri",
    "summary": "Chesterfield neighborhood guide for buyers: location, housing character, market data, and what to know before searching this West County area.",
    "url": "neighborhoods/chesterfield.html",
    "type": "neighborhood",
    "slug": "chesterfield",
    "group": "West County",
    "tag": "West County",
    "zips": ["63005", "63017", "63141"],
    "status": "published",
    "indexable": true,
    "template": "neighborhood"
  },
  {
    "id": "st-charles",
    "title": "St. Charles, Missouri",
    "summary": "St. Charles neighborhood guide for buyers: location, housing character, market data, and what to know before searching this St. Charles County area.",
    "url": "neighborhoods/st-charles.html",
    "type": "neighborhood",
    "slug": "st-charles",
    "group": "St. Charles County",
    "tag": "St. Charles Co.",
    "zips": ["63301", "63303", "63304"],
    "status": "published",
    "indexable": true,
    "template": "neighborhood"
  },
  {
    "id": "o-fallon",
    "title": "O'Fallon, Missouri",
    "summary": "O'Fallon neighborhood guide for buyers: location, housing character, market data, and what to know before searching this St. Charles County area.",
    "url": "neighborhoods/o-fallon.html",
    "type": "neighborhood",
    "slug": "o-fallon",
    "group": "St. Charles County",
    "tag": "St. Charles Co.",
    "zips": ["63366", "63368"],
    "status": "published",
    "indexable": true,
    "template": "neighborhood"
  },
  {
    "id": "st-peters",
    "title": "St. Peters, Missouri",
    "summary": "St. Peters neighborhood guide for buyers: location, housing character, market data, and what to know before searching this St. Charles County area.",
    "url": "neighborhoods/st-peters.html",
    "type": "neighborhood",
    "slug": "st-peters",
    "group": "St. Charles County",
    "tag": "St. Charles Co.",
    "zips": ["63376"],
    "status": "published",
    "indexable": true,
    "template": "neighborhood"
  },
  {
    "id": "wentzville",
    "title": "Wentzville, Missouri",
    "summary": "Wentzville neighborhood guide for buyers: location, housing character, market data, and what to know before searching this St. Charles County area.",
    "url": "neighborhoods/wentzville.html",
    "type": "neighborhood",
    "slug": "wentzville",
    "group": "St. Charles County",
    "tag": "St. Charles Co.",
    "zips": ["63385"],
    "status": "published",
    "indexable": true,
    "template": "neighborhood"
  },
  {
    "id": "lake-st-louis",
    "title": "Lake St. Louis, Missouri",
    "summary": "Lake St. Louis neighborhood guide for buyers: location, housing character, market data, and what to know before searching this St. Charles County area.",
    "url": "neighborhoods/lake-st-louis.html",
    "type": "neighborhood",
    "slug": "lake-st-louis",
    "group": "St. Charles County",
    "tag": "St. Charles Co.",
    "zips": ["63367"],
    "status": "published",
    "indexable": true,
    "template": "neighborhood"
  },
  {
    "id": "cottleville",
    "title": "Cottleville, Missouri",
    "summary": "Cottleville neighborhood guide for buyers: location, housing character, market data, and what to know before searching this St. Charles County area.",
    "url": "neighborhoods/cottleville.html",
    "type": "neighborhood",
    "slug": "cottleville",
    "group": "St. Charles County",
    "tag": "St. Charles Co.",
    "zips": ["63304"],
    "status": "published",
    "indexable": true,
    "template": "neighborhood"
  },
  {
    "id": "dardenne-prairie",
    "title": "Dardenne Prairie, Missouri",
    "summary": "Dardenne Prairie neighborhood guide for buyers: location, housing character, market data, and what to know before searching this St. Charles County area.",
    "url": "neighborhoods/dardenne-prairie.html",
    "type": "neighborhood",
    "slug": "dardenne-prairie",
    "group": "St. Charles County",
    "tag": "St. Charles Co.",
    "zips": ["63368"],
    "status": "published",
    "indexable": true,
    "template": "neighborhood"
  },
  {
    "id": "weldon-spring",
    "title": "Weldon Spring, Missouri",
    "summary": "Weldon Spring neighborhood guide for buyers: location, housing character, market data, and what to know before searching this St. Charles County area.",
    "url": "neighborhoods/weldon-spring.html",
    "type": "neighborhood",
    "slug": "weldon-spring",
    "group": "St. Charles County",
    "tag": "St. Charles Co.",
    "zips": ["63304"],
    "status": "published",
    "indexable": true,
    "template": "neighborhood"
  },
  {
    "id": "weldon-spring-heights",
    "title": "Weldon Spring Heights, Missouri",
    "summary": "Weldon Spring Heights neighborhood guide for buyers: location, housing character, market data, and what to know before searching this St. Charles County area.",
    "url": "neighborhoods/weldon-spring-heights.html",
    "type": "neighborhood",
    "slug": "weldon-spring-heights",
    "group": "St. Charles County",
    "tag": "St. Charles Co.",
    "zips": ["63304"],
    "status": "published",
    "indexable": true,
    "template": "neighborhood"
  },
  {
    "id": "josephville",
    "title": "Josephville, Missouri",
    "summary": "Josephville neighborhood guide for buyers: location, housing character, market data, and what to know before searching this St. Charles County area.",
    "url": "neighborhoods/josephville.html",
    "type": "neighborhood",
    "slug": "josephville",
    "group": "St. Charles County",
    "tag": "St. Charles Co.",
    "zips": ["63301"],
    "status": "published",
    "indexable": true,
    "template": "neighborhood"
  },
  {
    "id": "st-paul",
    "title": "St. Paul, Missouri",
    "summary": "St. Paul neighborhood guide for buyers: location, housing character, market data, and what to know before searching this St. Charles County area.",
    "url": "neighborhoods/st-paul.html",
    "type": "neighborhood",
    "slug": "st-paul",
    "group": "St. Charles County",
    "tag": "St. Charles Co.",
    "zips": ["63366"],
    "status": "published",
    "indexable": true,
    "template": "neighborhood"
  },
  {
    "id": "west-alton",
    "title": "West Alton, Missouri",
    "summary": "West Alton neighborhood guide for buyers: location, housing character, market data, and what to know before searching this St. Charles County area.",
    "url": "neighborhoods/west-alton.html",
    "type": "neighborhood",
    "slug": "west-alton",
    "group": "St. Charles County",
    "tag": "St. Charles Co.",
    "zips": ["63386"],
    "status": "published",
    "indexable": true,
    "template": "neighborhood"
  },
  {
    "id": "arnold",
    "title": "Arnold, Missouri",
    "summary": "Arnold neighborhood guide for buyers: location, housing character, market data, and what to know before searching this Jefferson County area.",
    "url": "neighborhoods/arnold.html",
    "type": "neighborhood",
    "slug": "arnold",
    "group": "Jefferson County",
    "tag": "Jefferson Co.",
    "zips": ["63010"],
    "status": "published",
    "indexable": true,
    "template": "neighborhood"
  },
  {
    "id": "festus",
    "title": "Festus, Missouri",
    "summary": "Festus neighborhood guide for buyers: location, housing character, market data, and what to know before searching this Jefferson County area.",
    "url": "neighborhoods/festus.html",
    "type": "neighborhood",
    "slug": "festus",
    "group": "Jefferson County",
    "tag": "Jefferson Co.",
    "zips": ["63028"],
    "status": "published",
    "indexable": true,
    "template": "neighborhood"
  },
  {
    "id": "crystal-city",
    "title": "Crystal City, Missouri",
    "summary": "Crystal City neighborhood guide for buyers: location, housing character, market data, and what to know before searching this Jefferson County area.",
    "url": "neighborhoods/crystal-city.html",
    "type": "neighborhood",
    "slug": "crystal-city",
    "group": "Jefferson County",
    "tag": "Jefferson Co.",
    "zips": ["63019"],
    "status": "published",
    "indexable": true,
    "template": "neighborhood"
  },
  {
    "id": "de-soto",
    "title": "De Soto, Missouri",
    "summary": "De Soto neighborhood guide for buyers: location, housing character, market data, and what to know before searching this Jefferson County area.",
    "url": "neighborhoods/de-soto.html",
    "type": "neighborhood",
    "slug": "de-soto",
    "group": "Jefferson County",
    "tag": "Jefferson Co.",
    "zips": ["63020"],
    "status": "published",
    "indexable": true,
    "template": "neighborhood"
  },
  {
    "id": "imperial",
    "title": "Imperial, Missouri",
    "summary": "Imperial neighborhood guide for buyers: location, housing character, market data, and what to know before searching this Jefferson County area.",
    "url": "neighborhoods/imperial.html",
    "type": "neighborhood",
    "slug": "imperial",
    "group": "Jefferson County",
    "tag": "Jefferson Co.",
    "zips": ["63052"],
    "status": "published",
    "indexable": true,
    "template": "neighborhood"
  },
  {
    "id": "high-ridge",
    "title": "High Ridge, Missouri",
    "summary": "High Ridge neighborhood guide for buyers: location, housing character, market data, and what to know before searching this Jefferson County area.",
    "url": "neighborhoods/high-ridge.html",
    "type": "neighborhood",
    "slug": "high-ridge",
    "group": "Jefferson County",
    "tag": "Jefferson Co.",
    "zips": ["63049"],
    "status": "published",
    "indexable": true,
    "template": "neighborhood"
  },
  {
    "id": "hillsboro",
    "title": "Hillsboro, Missouri",
    "summary": "Hillsboro neighborhood guide for buyers: location, housing character, market data, and what to know before searching this Jefferson County area.",
    "url": "neighborhoods/hillsboro.html",
    "type": "neighborhood",
    "slug": "hillsboro",
    "group": "Jefferson County",
    "tag": "Jefferson Co.",
    "zips": ["63050"],
    "status": "published",
    "indexable": true,
    "template": "neighborhood"
  },
  {
    "id": "house-springs",
    "title": "House Springs, Missouri",
    "summary": "House Springs neighborhood guide for buyers: location, housing character, market data, and what to know before searching this Jefferson County area.",
    "url": "neighborhoods/house-springs.html",
    "type": "neighborhood",
    "slug": "house-springs",
    "group": "Jefferson County",
    "tag": "Jefferson Co.",
    "zips": ["63051"],
    "status": "published",
    "indexable": true,
    "template": "neighborhood"
  },
  {
    "id": "barnhart",
    "title": "Barnhart, Missouri",
    "summary": "Barnhart neighborhood guide for buyers: location, housing character, market data, and what to know before searching this Jefferson County area.",
    "url": "neighborhoods/barnhart.html",
    "type": "neighborhood",
    "slug": "barnhart",
    "group": "Jefferson County",
    "tag": "Jefferson Co.",
    "zips": ["63012"],
    "status": "published",
    "indexable": true,
    "template": "neighborhood"
  },
  {
    "id": "cedar-hill",
    "title": "Cedar Hill, Missouri",
    "summary": "Cedar Hill neighborhood guide for buyers: location, housing character, market data, and what to know before searching this Jefferson County area.",
    "url": "neighborhoods/cedar-hill.html",
    "type": "neighborhood",
    "slug": "cedar-hill",
    "group": "Jefferson County",
    "tag": "Jefferson Co.",
    "zips": ["63016"],
    "status": "published",
    "indexable": true,
    "template": "neighborhood"
  }
];
