window.NEIGHBORHOODS_REGISTRY = [
  {
    "id": "central-west-end",
    "title": "Central West End, St. Louis",
    "summary": "Central West End neighborhood guide: what the Central West End is known for, where it sits, what buyers actually find there, and how it compares inside the St. Louis market.",
    "url": "central-west-end.html",
    "type": "neighborhood",
    "slug": "central-west-end",
    "status": "draft",
    "indexable": true,
    "seoPriority": 1,
    "launchTier": 1,
    "template": "neighborhood"
  },
  {
    "id": "tower-grove-south",
    "title": "Tower Grove South, St. Louis",
    "summary": "Tower Grove South neighborhood guide: boundaries, Tower Grove Park access, housing character, and what buyers should know before shopping this high-demand South City neighborhood.",
    "url": "tower-grove-south.html",
    "type": "neighborhood",
    "slug": "tower-grove-south",
    "status": "draft",
    "indexable": true,
    "seoPriority": 2,
    "launchTier": 1,
    "template": "neighborhood"
  },
  {
    "id": "shaw",
    "title": "Shaw, St. Louis",
    "summary": "Shaw neighborhood guide for buyers: Missouri Botanical Garden adjacency, Tower Grove access, historic district context, and what homes in Shaw actually feel like.",
    "url": "shaw.html",
    "type": "neighborhood",
    "slug": "shaw",
    "status": "draft",
    "indexable": true,
    "seoPriority": 3,
    "launchTier": 1,
    "template": "neighborhood"
  },
  {
    "id": "dogtown",
    "title": "Dogtown, St. Louis",
    "summary": "Dogtown neighborhood guide: what locals mean by Dogtown, the neighborhoods it includes, Forest Park access, and what buyers should know before choosing this St. Louis area.",
    "url": "dogtown.html",
    "type": "neighborhood",
    "slug": "dogtown",
    "status": "draft",
    "indexable": true,
    "seoPriority": 4,
    "launchTier": 1,
    "template": "neighborhood"
  },
  {
    "id": "soulard",
    "title": "Soulard, St. Louis",
    "summary": "Soulard neighborhood guide: official boundaries, market history, housing style, and what buyers should know before searching in one of St. Louis' best-known city neighborhoods.",
    "url": "soulard.html",
    "type": "neighborhood",
    "slug": "soulard",
    "status": "draft",
    "indexable": true,
    "seoPriority": 5,
    "launchTier": 1,
    "template": "neighborhood"
  },
  {
    "id": "lafayette-square",
    "title": "Lafayette Square, St. Louis",
    "summary": "Lafayette Square neighborhood guide: Lafayette Park, historic housing, official boundaries, and what buyers should know about this prestige St. Louis neighborhood.",
    "url": "lafayette-square.html",
    "type": "neighborhood",
    "slug": "lafayette-square",
    "status": "draft",
    "indexable": true,
    "seoPriority": 6,
    "launchTier": 1,
    "template": "neighborhood"
  },
  {
    "id": "the-hill",
    "title": "The Hill, St. Louis",
    "summary": "The Hill neighborhood guide: official boundaries, clay-mining history, Italian heritage, and what buyers should know before searching this St. Louis neighborhood.",
    "url": "the-hill.html",
    "type": "neighborhood",
    "slug": "the-hill",
    "status": "draft",
    "indexable": true,
    "seoPriority": 7,
    "launchTier": 1,
    "template": "neighborhood"
  },
  {
    "id": "benton-park",
    "title": "Benton Park, St. Louis",
    "summary": "Benton Park neighborhood guide: boundaries, park history, housing character, and what buyers should know about one of St. Louis' oldest residential areas.",
    "url": "benton-park.html",
    "type": "neighborhood",
    "slug": "benton-park",
    "status": "draft",
    "indexable": true,
    "seoPriority": 8,
    "launchTier": 1,
    "template": "neighborhood"
  },
  {
    "id": "st-louis-hills",
    "title": "St. Louis Hills, St. Louis",
    "summary": "St. Louis Hills neighborhood guide: official boundaries, Francis Park, development history, and what buyers should know about this sought-after southwest St. Louis neighborhood.",
    "url": "st-louis-hills.html",
    "type": "neighborhood",
    "slug": "st-louis-hills",
    "status": "draft",
    "indexable": true,
    "seoPriority": 9,
    "launchTier": 1,
    "template": "neighborhood"
  },
  {
    "id": "kirkwood",
    "title": "Kirkwood, Missouri",
    "summary": "Kirkwood neighborhood and city guide for buyers: population, downtown, historic train station, and what to expect in one of St. Louis County's most searched suburbs.",
    "url": "kirkwood.html",
    "type": "neighborhood",
    "slug": "kirkwood",
    "status": "draft",
    "indexable": true,
    "seoPriority": 10,
    "launchTier": 1,
    "template": "neighborhood"
  },
  {
    "id": "webster-groves",
    "title": "Webster Groves, Missouri",
    "summary": "Webster Groves guide for buyers: population, history, Old Webster and Old Orchard context, and what makes Webster Groves one of St. Louis County's most searched suburbs.",
    "url": "webster-groves.html",
    "type": "neighborhood",
    "slug": "webster-groves",
    "status": "draft",
    "indexable": true,
    "seoPriority": 11,
    "launchTier": 1,
    "template": "neighborhood"
  },
  {
    "id": "clayton",
    "title": "Clayton, Missouri",
    "summary": "Clayton buyer guide: official population, daytime workforce, Shaw Park, and what buyers should know about one of St. Louis County's most central and high-value cities.",
    "url": "clayton.html",
    "type": "neighborhood",
    "slug": "clayton",
    "status": "draft",
    "indexable": true,
    "seoPriority": 12,
    "launchTier": 1,
    "template": "neighborhood"
  },
  {
    "id": "university-city",
    "title": "University City, Missouri",
    "summary": "University City guide for buyers: population, Delmar Loop context, neighborhood variety, and what to know before shopping this large inner-ring St. Louis County city.",
    "url": "university-city.html",
    "type": "neighborhood",
    "slug": "university-city",
    "status": "draft",
    "indexable": true,
    "seoPriority": 13,
    "launchTier": 1,
    "template": "neighborhood"
  },
  {
    "id": "maplewood",
    "title": "Maplewood, Missouri",
    "summary": "Maplewood buyer guide: population, historic downtown, housing style, and what to know before searching this compact St. Louis County city.",
    "url": "maplewood.html",
    "type": "neighborhood",
    "slug": "maplewood",
    "status": "draft",
    "indexable": true,
    "seoPriority": 14,
    "launchTier": 1,
    "template": "neighborhood"
  },
  {
    "id": "ballwin",
    "title": "Ballwin, Missouri",
    "summary": "Ballwin guide for buyers: population, housing character, recreation anchors, and what to know before searching this major West County suburb.",
    "url": "ballwin.html",
    "type": "neighborhood",
    "slug": "ballwin",
    "status": "draft",
    "indexable": true,
    "seoPriority": 15,
    "launchTier": 1,
    "template": "neighborhood"
  },
  {
    "id": "chesterfield",
    "title": "Chesterfield, Missouri",
    "summary": "Chesterfield buyer guide: population, parks, city size, and what to know before searching one of West County's biggest and most established housing markets.",
    "url": "chesterfield.html",
    "type": "neighborhood",
    "slug": "chesterfield",
    "status": "draft",
    "indexable": true,
    "seoPriority": 16,
    "launchTier": 1,
    "template": "neighborhood"
  }
];
